### ISSUE TITLE
轮播图片的大小控制问题

### ISSUE THREAD

**Issue by elfive1992** [Vtrois/Snape#1]
这个主题确实是我看到的最好看的一个，目前只有两个小问题希望能改进下：
首先就是边栏小工具可否首页和文章页统一，很多情况下两者都是一样的，没必要分开设计；
其次就是轮播图片宽是固定的，高没有固定，如果每次都要求播放同样比例的图片，工作量就稍微大了，可否直接裁剪或缩放使轮播图片的显示大小一致，要不然下面的文章位置也会有略微变化。

**Comment by Vtrois** [comment]
done
