### ISSUE TITLE
导航栏菜单处的子项目不能缩回

### ISSUE THREAD

**Issue by cnlnn** [Vtrois/Snape#3]
在手机端浏览，菜单下的子项目展开后再次点击不能缩回，这是正常的吗？

**Comment by Vtrois** [comment]
不正常，有现场截图或者是console的报错吗?

**Comment by cnlnn** [comment]
展开之前
![2017-03-19 19-41-32](https://cloud.githubusercontent.com/assets/24188176/24080519/40738982-0cdc-11e7-9d4f-ec64ce1ea7a1.png)
展开之后
![2017-03-19 19-40-56](https://cloud.githubusercontent.com/assets/24188176/24080521/4b208f10-0cdc-11e7-8219-2bdaee4eac5a.png)
然后按菜单选项就无法缩回子项目了
![2017-03-19 19-41-08](https://cloud.githubusercontent.com/assets/24188176/24080547/a28ce4d8-0cdc-11e7-9520-221e7cfcd9f0.png)
不刷新的情况下切换为桌面版本时也是展开状态无法缩回
![2017-03-19 19-46-49](https://cloud.githubusercontent.com/assets/24188176/24080566/3184b760-0cdd-11e7-883a-8ef748ae6dc3.png)

**Comment by Vtrois** [comment]
done
